name: Setup UI Env
description: Setup node, python and call bootstrap script

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install packages
      shell: bash
      run: npm install --global yarn && yarn install:ci
