name: Pandaria Tests
on:
  # push:
  #   branches:
  #     - 'release-2.8*-cn*'
  pull_request:
    branches:
      - 'release-2.8*-cn*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
env:
  # Build the dashboard to use in tests. When set to false it will grab `latest` from CDN (useful for running e2e tests quickly)
  BUILD_DASHBOARD: true
jobs:
  unit-test:
    runs-on: repo-dashboard-runner-k8s
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/unit-tests

  i18n:
    runs-on: repo-dashboard-runner-k8s
    container: ubuntu:22.04
    needs:
      - unit-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run i18n lint
        uses: ./.github/actions/i18n-lint

  lint:
    runs-on: repo-dashboard-runner-k8s
    container: ubuntu:22.04
    needs:
      - i18n
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/lint
